from ._version import __version__
from .client import AsyncBanglaAI, BanglaAI
from .exceptions import (
    APIConnectionError,
    APIStatusError,
    AuthenticationError,
    BadRequestError,
    BanglaAIError,
    InternalServerError,
    NotFoundError,
    PermissionDeniedError,
    RateLimitError,
    ServiceUnavailableError,
    UpstreamServiceError,
)
from .types import (
    ApiKey,
    ASRResult,
    Attachment,
    Chat,
    ChatBranch,
    ChatProfile,
    CustomReferenceAudio,
    LiveKitToken,
    OCRJob,
    OCRPage,
    OCRRegion,
    OCRResult,
    OCRTiming,
    StreamChunk,
    StreamSession,
    TTSDiscovery,
    Turn,
    TurnChunk,
    UserProfile,
    VoiceReference,
    WsTicket,
    YouTubeASRResult,
)

__all__ = [
    "BanglaAI",
    "AsyncBanglaAI",
    "__version__",
    # Exceptions
    "BanglaAIError",
    "APIConnectionError",
    "APIStatusError",
    "BadRequestError",
    "AuthenticationError",
    "PermissionDeniedError",
    "NotFoundError",
    "RateLimitError",
    "InternalServerError",
    "UpstreamServiceError",
    "ServiceUnavailableError",
    # Types
    "UserProfile",
    "ApiKey",
    "WsTicket",
    "ChatProfile",
    "Chat",
    "Turn",
    "TurnChunk",
    "Attachment",
    "ChatBranch",
    "OCRRegion",
    "OCRPage",
    "OCRTiming",
    "OCRResult",
    "OCRJob",
    "ASRResult",
    "YouTubeASRResult",
    "StreamSession",
    "StreamChunk",
    "TTSDiscovery",
    "CustomReferenceAudio",
    "VoiceReference",
    "LiveKitToken",
]
